# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: |
          git fetch --prune --unshallow
        
      - name: Set up Python 3.6 environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3
          pip install heroku
          heroku plugins:install heroku-fork
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
          python -m unittest
        
      - name: auto pdoc
        run: |
          pdoc3 --html -o tmp back/
          rm -rf docs
          mkdir -p docs/
          mv tmp/back/* docs/
          rm -rf tmp/

      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          #git rm -rf __pycache__/
          #git rm -rf back/__pycache__/
          #git rm -rf test/__pycache__/
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "CI: Automated build push" -a | exit 0

      - name: Deploy to Heroku
        env:
            HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
            HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: |
            heroku create --region eu
            git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
            git push heroku main -f
            



      - name: Push changes
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
